# Generated by Django 3.0.2 on 2020-02-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='tags',
            field=models.ManyToManyField(null=True, related_name='article_tag', to='article.Tags'),
        ),
        migrations.DeleteModel(
            name='Tag_article',
        ),
    ]
