# Generated by Django 3.0.2 on 2020-02-10 12:34

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20200209_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='head_img',
            field=models.CharField(default='', max_length=125, verbose_name='主图'),
        ),
        migrations.AddField(
            model_name='articles',
            name='is_recommend',
            field=models.BooleanField(default=False, verbose_name='是否推荐'),
        ),
        migrations.AddField(
            model_name='articles',
            name='view_times',
            field=models.IntegerField(default=0, verbose_name='查看次数'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='body',
            field=ckeditor.fields.RichTextField(default=''),
        ),
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.CharField(default='', max_length=100, verbose_name='文章标题'),
        ),
    ]
