# Generated by Django 3.0.2 on 2020-02-19 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20200218_0949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='blog',
            new_name='article',
        ),
        migrations.AddField(
            model_name='comments',
            name='email',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='邮箱地址'),
        ),
        migrations.AddField(
            model_name='comments',
            name='is_show',
            field=models.BooleanField(default=True, verbose_name='是否显示出来'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='name',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='昵称'),
        ),
    ]
